version: '3'

services:
  app:
    container_name: graphitsql_backend
    
    # ? temp disabled - may be later it could be fun with docker registry
    # image: graphitsql_backend:${COMMIT_TAG}

    build:
      context: ./
      dockerfile: Dockerfile.staging
    env_file:
      - .env
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - docker_default-network
networks:
  docker_default-network:
    external: true