FROM node:20-alpine

USER node

WORKDIR /home/node

RUN mkdir -p node_modules \
  && chown -R node node_modules

COPY --chown=node:node . .

RUN npm install

RUN npm run build

CMD ["node", "dist/src/main.js"]
